"""empty message

Revision ID: 68ba118c2f81
Revises: cd146bb21a39
Create Date: 2022-02-21 17:19:22.607843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68ba118c2f81'
down_revision = 'cd146bb21a39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tbl_profiles_username'), 'tbl_profiles', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_profiles_username'), table_name='tbl_profiles')
    # ### end Alembic commands ###
