"""empty message

Revision ID: cd146bb21a39
Revises: 2bf7e316a86e
Create Date: 2022-02-21 17:17:56.687928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd146bb21a39'
down_revision = '2bf7e316a86e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_profiles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=11), nullable=True),
    sa.Column('first_name', sa.String(length=63), nullable=True),
    sa.Column('last_name', sa.String(length=63), nullable=True),
    sa.Column('avatar', sa.String(length=256), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['tbl_users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_profiles')
    # ### end Alembic commands ###
